CONTRIBUTING.md

@SethTisue and @ihostage already renamed the `master` branch in some play repos:
* https://github.com/playframework/cachecontrol/pull/163
* https://github.com/playframework/play-file-watch/pull/136
* https://github.com/playframework/play-json/pull/598
* https://github.com/playframework/play-soap/pull/282
* https://github.com/playframework/play-ws/pull/597
* https://github.com/playframework/twirl/pull/416
Now that we are centralising configs in the [`.github`](https://github.com/playframework/.github) repo it's a good idea that all repos have the same default branch name.
To change to `main` locally (if the remote to this repo is called `upstream`):
```sh
git branch -m master main # rename master to main (actually "move")
git fetch upstream
git branch -u upstream/main main # set upstream …
```

Rename master branch to main

---

.github/release-drafts/base.yml
.github/release-drafts/increasing-major-version.yml
.github/release-drafts/increasing-minor-version.yml
.github/release-drafts/increasing-patch-version.yml.yml
.github/release-drafts/minor-release.yml

Now that release drafter fixed bugs, added the header/footer feature and finally can correctly `_extend` other drafts ([see this comment](https://github.com/playframework/.github/pull/3#issuecomment-1027361907)), we can centralise the config in this `.github` repo.

Release draft templates for major/minor/patch releases

---

.github/workflows/sbt-matrix.yml
.github/workflows/sbt.yml
README.md

Add custom env variables for single and matrix workflows.
Add custom cache and include/exclude for matrix workflow.

Workflows improvements (ENVs, Caches, Include/Exclude)

---

.github/workflows/rtm.yml
README.md

**Goal**: unify configuration of Mergify and use one special marker for merging PRs automatically.
With this workflow our Mergify configuration in every repo will be very similar and when Mergify will add feature [fallback to organization (#4050)](https://github.com/Mergifyio/mergify-engine/pull/4050), we will can to drop all or change their to singleline `_extend`.

Add workflow "Mark Pull Request as Ready To Merge"

---

.github/workflows/binary-check.yml
.github/workflows/publish.yml
.github/workflows/sbt-matrix.yml
.github/workflows/sbt.yml

Tested in https://github.com/playframework/playframework/pull/11257
We can revert to version `...@v6.3` later again.

Provide CACHE_HIT_COURSIER (`steps` is not available from caller workflow)

---

.github/workflows/binary-check.yml
.github/workflows/cmd.yml
.github/workflows/publish.yml
README.md

* java/scala parameters of CMD as simple comma separated string
* Docs

Improve universal CMD task

---

README.md

Specially publish and binary check have the ref input now.

Switch to v2 in README

---

.github/workflows/publish.yml

When using `secrets: inherit` we can't make the secrets required in the reusable workflow, otherwise we get an error like [this one](https://github.com/playframework/twirl/actions/runs/2283859753):
> Secret username is required, but not provided while calling.
Tested here: https://github.com/playframework/twirl/runs/6329238847?check_suite_focus=true

Don't require secrets, otherwise we can't use `secrets: inherit`

---

.github/workflows/binary-check.yml
.github/workflows/cmd.yml
.github/workflows/publish.yml
README.md

We should release that as `v3.0.0` / `v3` eventually.

Drop Java 8, make Java 11 default

---

.github/release-drafts/base.yml

Eventually fixes https://github.com/playframework/play-meta/issues/216
We do mention the original author of a pull request now: https://github.com/playframework/playframework/blob/7f64632ddb96e8392a64c409075c94b132cd7e53/.mergify.yml#L4
but mergify is still mentioned:
<kbd><img width="600" src="https://user-images.githubusercontent.com/644927/195731183-df234d45-4967-4cf5-9e87-7b809b2d153b.png" /></kbd>
Details: https://github.com/release-drafter/release-drafter/#replacers
Because release notes will be generated on push workflows, I think it's ok to just merge this pull request and later we will see if it worked. Of course we could also temporary change the workflow version `...@rm-by-mergify`in a main branch of a repo but not sure if that is worth it. WDYT @ihostage?

Don't mention @mergify in release notes anymore

---

.github/workflows/cmd.yml

Fixes problem described in https://github.com/playframework/.github/pull/46#issuecomment-1285269979
In antory.yml we don't need to fix it because the output is not a json.

Clean up matrix json (no whitespaces etc.)

---

CONTRIBUTING.md

Currently we have a couple of contributor guidles, some of them are very very outdate, most of themhowever are quite similiar - but not the same:
* https://github.com/playframework/anorm/blob/631b5dbc83d636aed07f2f8fea7d3e634b57a46e/CONTRIBUTING.md
* https://github.com/playframework/playframework.com/blob/3ca657675e5c37c0e8a150c66b74e27e92628163/public/markdown/contributing.md
* published here: https://www.playframework.com/contributing
* https://github.com/playframework/playframework/blob/4dc76eb525d38c8f0f230bc6d4d44425d9067d7f/CONTRIBUTING.md
* https://github.com/playframework/play-mailer/blob/064ad43885101ca31c52e505e419ad3256f9524e/CONTRIBUTING.md
* https://github.com/playframework/play-slick/blob/6e874dee0619cfe5f0d48519b87d5d0af854e1ea/CONTRIBUTING.md
* …

Use one and only CONTRIBUTING file

---

RELEASING.md

This is WORK IN PROGRESS.
I merged the two files from https://github.com/playframework/play-meta/tree/main/releasing and a typical `RELEASE.md` from a repo (like https://github.com/playframework/play-json/blob/main/RELEASING.md).
So in the end we will have three section:
* how to release in general with release-by-tag, which now applies for all repos.
* second section for Play core framework because it is a bit special
* third section for sbt-web plugins (however maybe this will be removed or is not necessary, we will see)
I will improve this doc step-by-step, however I finally want to have this in one file only and we can link to it from the README.
All existing `RELEASING.md` are totally outdated. Doesn't look nice to have such outedated files in the repos.

Add one and only RELEASING.md

---

CODE_OF_CONDUCT.md

Fixes https://github.com/playframework/play-meta/issues/191
Like suggested by Greg this is just a copy of the CoC used by Scala, Lightbend and Typelevel. I basically just replaced contact details and the domains list. Nothing special.

Our "own" Code of Conduct

---

RELEASING.md

Got the warning 
```
OpenJDK 64-Bit Server VM warning: CodeCache is full. Compiler has been disabled.
OpenJDK 64-Bit Server VM warning: Try increasing the code cache size using -XX:ReservedCodeCacheSize=
CodeCache: size=131072Kb used=120457Kb max_used=122886Kb free=10614Kb
bounds [0x0000ffff20000000, 0x0000ffff28000000, 0x0000ffff28000000]
total_blobs=33203 nmethods=32314 adapters=787
compilation: disabled (not enough contiguous free space left)
```

Set ReservedCodeCacheSize=512m when releasing Play 2.8

---

.github/sync.yml
sbt/common.sbt

Related to https://github.com/playframework/play-meta/issues/252

Create common SBT settings with aliases for format/validate code

---

.github/workflows/binary-check.yml
.github/workflows/cmd.yml
.github/workflows/publish.yml

Current version generate a many warnings. For example [4014115839](https://github.com/playframework/playframework/actions/runs/4014115839)
This fix was checked in this run [4015390504](https://github.com/playframework/playframework/actions/runs/4015390504)
GHA warnings is gone 😄

Use latest `6.x` release of `coursier/cache-action`

---

.github/release-drafts/base.yml

They handed over the Play project to another company, that company might take over sponsorship as well, we will see :crossed_fingers:

Remove CiviForm from sponsors

---

.github/workflows/binary-check.yml
.github/workflows/cmd.yml
.github/workflows/publish.yml
README.md

See https://github.com/coursier/setup-action/pull/465, that PR has been released now: https://github.com/coursier/setup-action/releases/tag/v1.3.4

Add support for coursier --jvm-index in workflows using java

---

.github/workflows/binary-check.yml
.github/workflows/cmd.yml
.github/workflows/publish.yml
README.md

Fixes https://github.com/playframework/playframework/issues/12007

Improve Coursier cache

---

.github/workflows/antora.yml
.github/workflows/binary-check.yml
.github/workflows/cmd.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/publish.yml

Makes sure we do not rely on dependencies from these deprecated repos anymore, across all our repos.
Related:
- https://github.com/sbt/sbt/issues/7484

Block deprecated repos in `/etc/hosts`

---

.github/release-drafts/base.yml

https://www.depop.com/ :partying_face: 
Official announcement follows by the end of this week.
I want to cut Play 3.0.6 before, but want to have their logo on the release notes already.
I also reordered the logos like in 
- https://github.com/playframework/playframework.com/pull/600
because we need a third row anyway (no preferences made really in ordering).

Add Depop as premium sponsor

---

.github/workflows/antora.yml
.github/workflows/binary-check.yml
.github/workflows/cmd.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/publish.yml
.github/workflows/rtm.yml
.github/workflows/sync.yml

> The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025. To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 20.04. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:
> 
>     March 4 14:00 UTC – 22:00 UTC
>     March 11 13:00 UTC – 21:00 UTC
>     March 18 13:00 UTC – 21:00 UTC
>     March 25 13:00 UTC – 21:00 UTC
> 
> What you need to do
> 
> Jobs using the ubuntu-20.04 YAML workflow label should be updated to ubuntu-22.04, ubuntu-24.04 or ubuntu-latest. You can always get up-to-date information on our tools by reading about the software in the [runner images repository](https://github.com/actions/runner-images).

Run on `ubuntu-24.04`
