playframework/.github

- FUNDING.yml
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
> Add GitHub sponsors to funding.yml

- .github/release-drafts/base.yml
@ProChirathF @prosasankad :rocket:
> Add Pronto Software as premium sponsor

- .github/workflows/binary-check.yml
- .github/workflows/publish.yml
- .github/workflows/sbt-matrix.yml
- .github/workflows/sbt.yml
Let's see if that works with Java 17.
It should since its in the index here: https://github.com/coursier/jvm-index/blob/master/index.json
> Switch to Adoptium's Temurin OpenJDK

- .github/workflows/binary-check.yml
- .github/workflows/publish.yml
- .github/workflows/sbt-matrix.yml
- .github/workflows/sbt.yml
> Update `coursier/setup-action` to `1.2.0-M3`

- .github/workflows/binary-check.yml
- .github/workflows/cmd.yml
- .github/workflows/publish.yml
https://github.com/coursier/setup-action/releases/tag/v1.2.0
> coursier/setup-action v1.2.0 final

- .github/release-drafts/base.yml
> Add The Guardian as premium sponsor

- .github/sync.yml
- .github/workflows/sync.yml
- .mergify.yml
Fixes https://github.com/playframework/play-meta/issues/243
> Sync Mergify settings between all repositories

- .github/workflows/binary-check.yml
- .github/workflows/cmd.yml
- .github/workflows/publish.yml
* https://github.com/actions/cache/releases
* https://github.com/coursier/setup-action/releases/tag/v1.2.1
> Upgrade actions

- .github/release-drafts/base.yml
> Fix release draft, wrong div

- .github/workflows/publish.yml
Inspired by https://github.com/orgs/community/discussions/12269
> Use idiomatic way for disabling publishing from fork

- .github/workflows/antora.yml
- .github/workflows/cmd.yml
> #45 Use environment file instead `set-output`

- .github/mergify.yml
Inspired by https://github.com/playframework/play-socket.io/pull/232
> Remove `merge-when-green` label after closing PR

- RELEASING.md
There are a couple of people joining each week: https://www.linkedin.com/groups/3818467/
> Also announce releasein the LinkedIn group

- .github/release-drafts/base.yml
https://nulab.com/
Replaces Iterable.
> Add Nulab as premium sponsor

- RELEASING.md
* No need to publish omnidoc anymore, see https://github.com/playframework/omnidoc/issues/128
* Add posts TODOs for open collective, github sponsor and the scala reddit
> Update RELEASING docs

- .github/release-drafts/base.yml
https://www.sprypoint.com/
Official announcement follows.
> Add SpryPoint as premium sponsor

- .github/release-drafts/base.yml
This annoyed me quite a while already.
> Add a new line in release draft

- .github/workflows/antora.yml
See https://github.com/asciidoctor/asciidoctor-tabs
> Support Asciidoctor Tabs.

- .github/mergify.yml
Also rename `method` parameter to actual name `merge_method`
https://changelog.mergify.com/changelog/rename-queue-action-method-option-in-mergemethod
> Support rebase/squash merge by tag

- .github/mergify.yml
> Remove all merge action tags after close

- .github/mergify.yml
Alternative to #92 which seems a bit weird.
> Refactor mergify

- .github/release-drafts/base.yml
Just like
- https://github.com/playframework/playframework/pull/13247
> Update informaticon logo
